(()=>{
  const KEY='spellRushProgress';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(_){return {}}};
  const write=v=>{try{localStorage.setItem(KEY,JSON.stringify(v))}catch(_){} };
  const style=document.createElement('style');
  style.textContent='.achievements{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}.achievement{position:relative;display:flex;gap:8px;align-items:flex-start;padding:9px 8px;border:1px solid #204354;border-radius:11px;background:#071b28;min-height:58px}.achievement.done{border-color:#3c9b82;background:linear-gradient(135deg,#0c2a32,#0a2430)}.achievement.done:after{content:"✓";position:absolute;right:7px;top:5px;color:#5ee6a0;font-weight:800}.achievement-icon{font-size:19px;filter:grayscale(1);opacity:.62}.achievement.done .achievement-icon{filter:none;opacity:1}.achievement strong{display:block;font-size:11.5px}.achievement small{display:block;color:#8fb0bd;font-size:10.5px;line-height:1.3;margin-top:3px}.achievement-progress{height:3px;border-radius:99px;background:#102b38;margin-top:5px;overflow:hidden}.achievement-progress i{display:block;height:100%;background:linear-gradient(90deg,#ffc857,#5ee6a0)}@media(max-width:520px){.achievements{grid-template-columns:1fr}.miss-item{flex-wrap:wrap}.app{padding-bottom:calc(14px + env(safe-area-inset-bottom))}}';
  document.head.appendChild(style);
  const defs=[['first','⚡','初次命中','累计答对 1 个词',1],['combo','🔥','火力全开','最高连击达到 5',5],['daily','🌟','今日完成','一天答对 5 个词',5],['master','🛡️','词汇守护者','答对过 10 个不同的词',10],['perfect','💎','无伤通关','一局答对全部 10 题',1],['scholar','🏆','词汇学徒','累计答对 50 个词',50]];
  function ensure(){let h=document.getElementById('achievements');if(h)return h;const side=document.querySelector('.side');if(!side)return null;const sec=document.createElement('section');sec.innerHTML='<h2>里程碑</h2><p class="tip">完成小目标，解锁称号；进度保存在本机。</p><div class="achievements" id="achievements"></div>';const anchor=side.querySelector('section:nth-of-type(3)')||side.lastElementChild;side.insertBefore(sec,anchor);return sec.querySelector('#achievements')}
  let lastSignature='';
  function update(){const h=ensure();if(!h)return;const d=read(),today=new Date().toISOString().slice(0,10);d.seen=d.seen||[];const good=d.seen.filter(x=>x.ok),unique=new Set(good.map(x=>x.word)).size;const streak=Math.max(d.bestStreak||0,Number(document.getElementById('streak')?.textContent)||0);if(streak>(d.bestStreak||0)){d.bestStreak=streak;write(d)};const vals={first:d.learned||0,combo:d.bestStreak||0,daily:d.dailyDate===today?(d.daily||0):0,master:unique,perfect:d.perfectRuns||0,scholar:d.learned||0};const signature=defs.map(a=>Math.min(a[4],vals[a[0]]||0)).join('|');if(signature===lastSignature)return;lastSignature=signature;h.innerHTML=defs.map(a=>{const v=Math.min(a[4],vals[a[0]]||0),done=v>=a[4];return '<div class="achievement '+(done?'done':'')+'"><span class="achievement-icon">'+a[1]+'</span><div><strong>'+a[2]+'</strong><small>'+a[3]+' · '+v+'/'+a[4]+'</small><div class="achievement-progress"><i style="width:'+Math.round(v/a[4]*100)+'%"></i></div></div></div>'}).join('')}
  function feedback(){const f=document.getElementById('feedback'),p=document.getElementById('pattern');if(!f||!p||!f.classList.contains('bad'))return;const m=f.textContent.match(/正确答案：\s*([a-z][a-z' -]*)/i);if(!m)return;const w=m[1].trim();const next=w.split('').map((c,i)=>'<span class="ch '+(i?'fill':'first')+'">'+(c===' '?'&nbsp;':c)+'</span>').join('');if(p.innerHTML!==next)p.innerHTML=next}
  new MutationObserver(()=>{update();feedback()}).observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class']});
  update();setInterval(update,1000);
})();
